In [1]:
from sympy import *
from warnings import filterwarnings
init_printing(use_latex = 'mathjax')
filterwarnings('ignore')

In [2]:
lamda = symbols('lamda')

In [3]:
A = Matrix([[-2, 1, 0], [1, -2, 1], [0, 1, -2]])
I = eye(3)
A, I 

⎛⎡-2  1   0 ⎤  ⎡1  0  0⎤⎞
⎜⎢          ⎥  ⎢       ⎥⎟
⎜⎢1   -2  1 ⎥, ⎢0  1  0⎥⎟
⎜⎢          ⎥  ⎢       ⎥⎟
⎝⎣0   1   -2⎦  ⎣0  0  1⎦⎠

In [4]:
(A - lamda * I)

⎡-λ - 2    1       0   ⎤
⎢                      ⎥
⎢  1     -λ - 2    1   ⎥
⎢                      ⎥
⎣  0       1     -λ - 2⎦

In [5]:
(A - lamda * I).det()

              3    
2⋅λ + (-λ - 2)  + 4

In [6]:
((A - lamda * I).det()).factor()

         ⎛ 2          ⎞
-(λ + 2)⋅⎝λ  + 4⋅λ + 2⎠

In [7]:
A.eigenvals()

{-2: 1, -2 - √2: 1, -2 + √2: 1}

In [8]:
A.eigenvects()

⎡⎛       ⎡⎡-1⎤⎤⎞  ⎛            ⎡⎡ 1 ⎤⎤⎞  ⎛            ⎡⎡1 ⎤⎤⎞⎤
⎢⎜       ⎢⎢  ⎥⎥⎟  ⎜            ⎢⎢   ⎥⎥⎟  ⎜            ⎢⎢  ⎥⎥⎟⎥
⎢⎜-2, 1, ⎢⎢0 ⎥⎥⎟, ⎜-2 - √2, 1, ⎢⎢-√2⎥⎥⎟, ⎜-2 + √2, 1, ⎢⎢√2⎥⎥⎟⎥
⎢⎜       ⎢⎢  ⎥⎥⎟  ⎜            ⎢⎢   ⎥⎥⎟  ⎜            ⎢⎢  ⎥⎥⎟⎥
⎣⎝       ⎣⎣1 ⎦⎦⎠  ⎝            ⎣⎣ 1 ⎦⎦⎠  ⎝            ⎣⎣1 ⎦⎦⎠⎦

In [9]:
Q = Matrix([[0, -1], [1, 0]])
Q

⎡0  -1⎤
⎢     ⎥
⎣1  0 ⎦

In [10]:
Q.eigenvals()

{-ⅈ: 1, ⅈ: 1}

In [11]:
Q.eigenvects()


⎡⎛       ⎡⎡-ⅈ⎤⎤⎞  ⎛      ⎡⎡ⅈ⎤⎤⎞⎤
⎢⎜-ⅈ, 1, ⎢⎢  ⎥⎥⎟, ⎜ⅈ, 1, ⎢⎢ ⎥⎥⎟⎥
⎣⎝       ⎣⎣1 ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

## Power method (from Dr.Chrysafinos Notes Ntua )


In [30]:
import numpy as np 
A = np.array([[-2, 1, 0], [1, -2, 1], [0, 1, -2]]);A

array([[-2,  1,  0],
       [ 1, -2,  1],
       [ 0,  1, -2]])

In [31]:
x = np.array([-1, 2, 3]);x

array([-1,  2,  3])

In [24]:
y1 = A@x;y1

array([ 4, -2, -4])

In [25]:
y1/x

array([-4.        , -1.        , -1.33333333])

In [26]:
x1= y1 / np.linalg.norm(y1);x1

array([ 0.66666667, -0.33333333, -0.66666667])

In [27]:
y2 = A@x1;y2

array([-1.66666667,  0.66666667,  1.        ])

In [28]:
y2 / x1

array([-2.5, -2. , -1.5])

In [29]:
x2 = y2 / np.linalg.norm(y2);x2

array([-0.81110711,  0.32444284,  0.48666426])