# Conjugate Gradient Method (from Dr.Chrysafinos Notes Ntua )

In [54]:
import numpy as np

In [55]:
def conjGrad(A,x,b,tol = 1e-3,N = 1000):
    r = b - A@x
    p = r.copy()
    for i in range(N):
        Ap = A@p
        alpha = (p@r) / (p@Ap)
        x = x + alpha*p
        r = b - A@x
        if np.sqrt(np.sum((r**2))) < tol:
            print('Iterations executed:', i+1)
            break
        else:
            beta = - (r@Ap) /  (p@Ap)
            w = beta*p
            p = r + w
    return x 

In [56]:
a = np.array([[3, 2, -1], [2, -1, 1], [-1, 1, -1]]) 
b = np.array([1, -2, 0])
x = np.array([0, 1, 2])

conjGrad(a,x,b)

Iterations executed: 3


array([-2.,  9., 11.])

In [57]:
A = np.array([[4, -1, 1], [-1, 4, -2], [1, -2, 4]]);A

array([[ 4, -1,  1],
       [-1,  4, -2],
       [ 1, -2,  4]])

In [58]:
b = np.array([12, -1, 5]);b

array([12, -1,  5])

In [59]:
x = np.array([0, 0, 0]);x

array([0, 0, 0])

In [60]:
conjGrad(A,x,b)

Iterations executed: 3


array([3., 1., 1.])

$$r_{0} = b - A x_{0} $$

In [8]:
r0 = b - a@x;r0

array([12, -1,  5])

$$s_{0} = r_{0}$$

In [9]:
s0 = r0 
As0 = A@s0;As0

array([ 54, -26,  34])

$$a_{0} = \frac{s_{0}^{T}r_{0}}{ s_{0}^{T}As_{0} }$$

In [10]:
a0 = (s0.T@r0) / (s0.T@As0)   ;a0

0.2014218009478673

$$x_{1} = x_{0}+a_{0}s_{0}$$

In [11]:
x1 = x+a0*s0;x1

array([ 2.41706161, -0.2014218 ,  1.007109  ])

$$r_{1} = b - A x_{1} $$

In [12]:
r1 = b - A@x1;r1

array([ 1.12322275,  4.23696682, -1.84834123])

$$\beta_{0} = - \dfrac{r_{1}^{T}As_{0}}{s_{0}As_{0}} $$

In [13]:
b0 = - (r1.T@A@s0)/(s0.T@A@s0);b0

0.13311695604321552

$$s_{1} = r_{1}+\beta_{0}s_{0}$$

In [14]:
s1 = r1+b0*s0;s1

array([ 2.72062622,  4.10384987, -1.18275645])

$$A s_{1}$$

In [15]:
As1 = A@s1;As1

array([  5.59589856,  16.06028616, -10.21809932])

$$a_{1} = \frac{s_{1}^{T}r_{1}}{ s_{1}^{T}As_{1} }$$

In [16]:
a1 = (s1.T@r1) / (s1.T@As1)   ;a1

0.24276073539239712

$$x_{2} = x_{1}+a_{1}s_{1}$$

In [17]:
x2 = x1+a1*s1;x2

array([3.07752283, 0.79483181, 0.71998218])

$$r_{1} = b - A x_{1} $$

In [18]:
r2 = b - A@x2;r2

array([-0.2352417 ,  0.33815995,  0.63221207])

$$\beta_{0} = - \dfrac{r_{1}^{T}As_{0}}{s_{0}As_{0}} $$

In [19]:
b1 = - (r2.T@A@s1)/(s1.T@A@s1);b1

0.025160665926695365

$$s_{2} = r_{2}+\beta_{1}s_{1}$$

In [20]:
s2 = r2+b1*s1;s2

array([-0.16678893,  0.44141554,  0.60245313])

$$A s_{2}$$

In [21]:
As2 = A@s2;As2

array([-0.50611815,  0.72754483,  1.36019252])

$$a_{2} = \frac{s_{2}^{T}r_{2}}{ s_{2}^{T}As_{2} }$$

In [22]:
a2 = (s2@r2.T) / (s2.T@As2)   ;a2

0.4647960240215365

$$x_{3} = x_{2}+a_{2}s_{2}$$

In [23]:
x3 = x2+a2*s2;x3

array([3., 1., 1.])