# Conjugate Gradient Method (from Dr.Chrysafinos Notes Ntua)

In [66]:
import numpy as np

In [67]:
def conjGrad(A,x,b,tol = 1e-3,N = 1000):
    r = b - A@x
    p = r.copy()
    for i in range(N):
        Ap = A@p
        alpha = (p@r) / (p@Ap)
        x = x + alpha*p
        r = b - A@x
        if np.sqrt(np.sum((r**2))) < tol:
            print('Iterations executed:', i+1)
            break
        else:
            beta = - (r@Ap) /  (p@Ap)
            w = beta*p
            p = r + w
    return x 

In [69]:
A = np.array([[5, 2], [2, 1]]);A

array([[5, 2],
       [2, 1]])

In [70]:
b = np.array([1,1]);b

array([1, 1])

In [71]:
x = np.array([0, 0]);x

array([0, 0])

In [72]:
conjGrad(A,x,b)

Iterations executed: 2


array([-1.,  3.])

## Step by step calculation of CG method 


$$r_{0} = b - A x_{0} $$

In [74]:
r0 = b - A@x;r0

array([1, 1])

$$s_{0} = r_{0}$$

In [75]:
s0 = r0 
As0 = A@s0;As0

array([7, 3])

$$a_{0} = \frac{s_{0}^{T}r_{0}}{ s_{0}^{T}As_{0} }$$

In [76]:
a0 = (s0.T@r0) / (s0.T@As0)   ;a0

0.2

$$x_{1} = x_{0}+a_{0}s_{0}$$

In [77]:
x1 = x+a0*s0;x1

array([0.2, 0.2])

$$r_{1} = b - A x_{1} $$

In [78]:
r1 = b - A@x1;r1

array([-0.4,  0.4])

$$\beta_{0} = - \dfrac{r_{1}^{T}As_{0}}{s_{0}As_{0}} $$

In [79]:
b0 = - (r1.T@A@s0)/(s0.T@A@s0);b0

0.15999999999999998

$$s_{1} = r_{1}+\beta_{0}s_{0}$$

In [80]:
s1 = r1+b0*s0;s1

array([-0.24,  0.56])

$$A s_{1}$$

In [81]:
As1 = A@s1;As1

array([-0.08,  0.08])

$$a_{1} = \frac{s_{1}^{T}r_{1}}{ s_{1}^{T}As_{1} }$$

In [82]:
a1 = (s1.T@r1) / (s1.T@As1)   ;a1

5.0

$$x_{2} = x_{1}+a_{1}s_{1}$$

In [83]:
x2 = x1+a1*s1;x2

array([-1.,  3.])

$$r_{1} = b - A x_{1} $$

In [84]:
r2 = b - A@x2;r2

array([8.8817842e-16, 4.4408921e-16])

$$\beta_{0} = - \dfrac{r_{1}^{T}As_{0}}{s_{0}As_{0}} $$

In [85]:
b1 = - (r2.T@A@s1)/(s1.T@A@s1);b1

5.55111512312579e-16

$$s_{2} = r_{2}+\beta_{1}s_{1}$$

In [86]:
s2 = r2+b1*s1;s2

array([7.54951657e-16, 7.54951657e-16])

$$A s_{2}$$

In [87]:
As2 = A@s2;As2

array([5.28466160e-15, 2.26485497e-15])

$$a_{2} = \frac{s_{2}^{T}r_{2}}{ s_{2}^{T}As_{2} }$$

In [88]:
a2 = (s2@r2.T) / (s2.T@As2)   ;a2

0.17647058823529413

$$x_{3} = x_{2}+a_{2}s_{2}$$

In [89]:
x3 = x2+a2*s2;x3

array([-1.,  3.])